---
language: python
python: "3.6"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y curl

install:
  - pip install ansible

  # Create symlink with actual role name
  - ln -s ansible-coreos-bootstrap ../coreos_bootstrap

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  - "ansible-playbook -i tests/inventory tests/test.yml --syntax-check"
