---
- name: Check if bootstrap is needed
  raw: "stat $HOME/.bootstrapped_{{ python_version }}_{{ pypy_version }}"
  register: need_bootstrap
  ignore_errors: True
  changed_when: False
  check_mode: no

- name: Run bootstrap.sh
  script: bootstrap.sh
  environment:
    PYTHON_VERSION: "{{ python_version }}"
    PYPY_VERSION: "{{ pypy_version }}"
  when: need_bootstrap is failed
  notify: bootstrap changed

- name: Check if we need to install pip
  shell: "{{ ansible_python_interpreter }} -m pip --version"
  register: need_pip
  ignore_errors: True
  changed_when: False
  when: need_bootstrap is failed
  check_mode: no

- name: Install pip
  shell: "curl https://bootstrap.pypa.io/pip/2.7/get-pip.py | {{ ansible_python_interpreter }}"
  args:
    warn: false
  when: need_pip is failed
  notify: bootstrap changed

- name: Install pip launcher
  copy:
    src: runner
    dest: ~/bin/pip
    mode: 0755
  when: need_pip is failed
  notify: bootstrap changed
